# Generated by Django 6.0.6 on 2026-06-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_reported', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_date', models.DateTimeField(auto_now_add=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.assetinstance')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status_after', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_maintenance', to='inventory.assetstatus')),
                ('status_before', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_maintenance', to='inventory.assetstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
