
ICT_EQUIPMENT = [
    {
        "item_code": "ICT-0001",
        "name": "Dell OptiPlex Desktop Computer",
        "category": "ICT Equipment",
        "manufacturer": "Dell Technologies",
        "brand": "Dell",
        "model": "OptiPlex 7010",
        "unit": "Piece",
        "type": "Asset",
        "cost": 2500000,
        "reorder_level": 2,
    },
    {
        "item_code": "ICT-0002",
        "name": "HP ProBook Laptop",
        "category": "ICT Equipment",
        "manufacturer": "HP Inc.",
        "brand": "HP",
        "model": "ProBook 450 G9",
        "unit": "Piece",
        "type": "Asset",
        "cost": 3800000,
        "reorder_level": 2,
    },
    {
        "item_code": "ICT-0003",
        "name": "Lenovo ThinkCentre Desktop",
        "category": "ICT Equipment",
        "manufacturer": "Lenovo",
        "brand": "Lenovo",
        "model": "ThinkCentre M720",
        "unit": "Piece",
        "type": "Asset",
        "cost": 2400000,
        "reorder_level": 2,
    },
    {
        "item_code": "ICT-0004",
        "name": "Dell PowerEdge Server",
        "category": "ICT Equipment",
        "manufacturer": "Dell Technologies",
        "brand": "Dell",
        "model": "PowerEdge R740",
        "unit": "Piece",
        "type": "Asset",
        "cost": 18500000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0005",
        "name": "HP LaserJet Printer",
        "category": "ICT Equipment",
        "manufacturer": "HP Inc.",
        "brand": "HP",
        "model": "LaserJet M404dn",
        "unit": "Piece",
        "type": "Asset",
        "cost": 1450000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0006",
        "name": "Epson EcoTank Printer",
        "category": "ICT Equipment",
        "manufacturer": "Epson",
        "brand": "Epson",
        "model": "L3250",
        "unit": "Piece",
        "type": "Asset",
        "cost": 980000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0007",
        "name": "Cisco Network Switch",
        "category": "ICT Equipment",
        "manufacturer": "Cisco Systems",
        "brand": "Cisco",
        "model": "Catalyst 2960",
        "unit": "Piece",
        "type": "Asset",
        "cost": 2100000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0008",
        "name": "MikroTik Router",
        "category": "ICT Equipment",
        "manufacturer": "MikroTik",
        "brand": "MikroTik",
        "model": "RB4011",
        "unit": "Piece",
        "type": "Asset",
        "cost": 1250000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0009",
        "name": "APC Smart UPS",
        "category": "ICT Equipment",
        "manufacturer": "APC",
        "brand": "APC",
        "model": "SMT1500",
        "unit": "Piece",
        "type": "Asset",
        "cost": 3400000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0010",
        "name": "42U Network Rack",
        "category": "ICT Equipment",
        "manufacturer": "APC",
        "brand": "APC",
        "model": "NetShelter SX",
        "unit": "Piece",
        "type": "Asset",
        "cost": 5200000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0011",
        "name": "External Hard Drive",
        "category": "ICT Equipment",
        "manufacturer": "Seagate",
        "brand": "Seagate",
        "model": "Expansion 2TB",
        "unit": "Piece",
        "type": "Asset",
        "cost": 420000,
        "reorder_level": 3,
    },
    {
        "item_code": "ICT-0012",
        "name": "USB Flash Drive",
        "category": "ICT Equipment",
        "manufacturer": "SanDisk",
        "brand": "SanDisk",
        "model": "Ultra 64GB",
        "unit": "Piece",
        "type": "Consumable",
        "cost": 45000,
        "reorder_level": 20,
    },
    {
        "item_code": "ICT-0013",
        "name": "Wireless Keyboard",
        "category": "ICT Equipment",
        "manufacturer": "Logitech",
        "brand": "Logitech",
        "model": "K270",
        "unit": "Piece",
        "type": "Asset",
        "cost": 120000,
        "reorder_level": 5,
    },
    {
        "item_code": "ICT-0014",
        "name": "Wireless Mouse",
        "category": "ICT Equipment",
        "manufacturer": "Logitech",
        "brand": "Logitech",
        "model": "M185",
        "unit": "Piece",
        "type": "Asset",
        "cost": 70000,
        "reorder_level": 5,
    },
    {
        "item_code": "ICT-0015",
        "name": "24-inch LED Monitor",
        "category": "ICT Equipment",
        "manufacturer": "Dell Technologies",
        "brand": "Dell",
        "model": "P2422H",
        "unit": "Piece",
        "type": "Asset",
        "cost": 780000,
        "reorder_level": 3,
    },
    {
        "item_code": "ICT-0016",
        "name": "Web Camera",
        "category": "ICT Equipment",
        "manufacturer": "Logitech",
        "brand": "Logitech",
        "model": "C920",
        "unit": "Piece",
        "type": "Asset",
        "cost": 420000,
        "reorder_level": 2,
    },
    {
        "item_code": "ICT-0017",
        "name": "Conference Speakerphone",
        "category": "ICT Equipment",
        "manufacturer": "Jabra",
        "brand": "Jabra",
        "model": "Speak 510",
        "unit": "Piece",
        "type": "Asset",
        "cost": 950000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0018",
        "name": "Barcode Scanner",
        "category": "ICT Equipment",
        "manufacturer": "Zebra Technologies",
        "brand": "Zebra",
        "model": "DS2208",
        "unit": "Piece",
        "type": "Asset",
        "cost": 680000,
        "reorder_level": 2,
    },
    {
        "item_code": "ICT-0019",
        "name": "Label Printer",
        "category": "ICT Equipment",
        "manufacturer": "Brother",
        "brand": "Brother",
        "model": "QL-800",
        "unit": "Piece",
        "type": "Asset",
        "cost": 850000,
        "reorder_level": 1,
    },
    {
        "item_code": "ICT-0020",
        "name": "Interactive Smart Display",
        "category": "ICT Equipment",
        "manufacturer": "Samsung",
        "brand": "Samsung",
        "model": "Flip Pro",
        "unit": "Piece",
        "type": "Asset",
        "cost": 12500000,
        "reorder_level": 1,
    },
]

MACHINERY = [

# ================= CNC =================

{
    "item_code": "MAC-0001",
    "name": "CNC Milling Machine",
    "category": "Machinery",
    "manufacturer": "DMG MORI",
    "brand": "DMG MORI",
    "model": "CMX 600 V",
    "unit": "Piece",
    "type": "Asset",
    "cost": 285000000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0002",
    "name": "CNC Lathe Machine",
    "category": "Machinery",
    "manufacturer": "Haas Automation",
    "brand": "Haas",
    "model": "ST-20",
    "unit": "Piece",
    "type": "Asset",
    "cost": 240000000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0003",
    "name": "Vertical Machining Center",
    "category": "Machinery",
    "manufacturer": "Mazak",
    "brand": "Mazak",
    "model": "VCN-530C",
    "unit": "Piece",
    "type": "Asset",
    "cost": 320000000,
    "reorder_level": 1,
},

# ================= Welding =================

{
    "item_code": "MAC-0004",
    "name": "Arc Welding Machine",
    "category": "Machinery",
    "manufacturer": "Lincoln Electric",
    "brand": "Lincoln",
    "model": "Power Wave S350",
    "unit": "Piece",
    "type": "Asset",
    "cost": 8200000,
    "reorder_level": 2,
},

{
    "item_code": "MAC-0005",
    "name": "MIG Welding Machine",
    "category": "Machinery",
    "manufacturer": "Miller Electric",
    "brand": "Miller",
    "model": "Millermatic 252",
    "unit": "Piece",
    "type": "Asset",
    "cost": 12500000,
    "reorder_level": 2,
},

{
    "item_code": "MAC-0006",
    "name": "TIG Welding Machine",
    "category": "Machinery",
    "manufacturer": "Lincoln Electric",
    "brand": "Lincoln",
    "model": "Aspect 230",
    "unit": "Piece",
    "type": "Asset",
    "cost": 15000000,
    "reorder_level": 2,
},

{
    "item_code": "MAC-0007",
    "name": "Plasma Cutting Machine",
    "category": "Machinery",
    "manufacturer": "Hypertherm",
    "brand": "Hypertherm",
    "model": "Powermax45 XP",
    "unit": "Piece",
    "type": "Asset",
    "cost": 14500000,
    "reorder_level": 1,
},

# ================= Wood =================

{
    "item_code": "MAC-0008",
    "name": "Wood Lathe Machine",
    "category": "Machinery",
    "manufacturer": "JET Tools",
    "brand": "JET",
    "model": "JWL-1221VS",
    "unit": "Piece",
    "type": "Asset",
    "cost": 7500000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0009",
    "name": "Band Saw",
    "category": "Machinery",
    "manufacturer": "Makita",
    "brand": "Makita",
    "model": "LB1200F",
    "unit": "Piece",
    "type": "Asset",
    "cost": 4600000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0010",
    "name": "Thickness Planer",
    "category": "Machinery",
    "manufacturer": "DeWalt",
    "brand": "DeWalt",
    "model": "DW735",
    "unit": "Piece",
    "type": "Asset",
    "cost": 3800000,
    "reorder_level": 1,
},

# ================= General Workshop =================

{
    "item_code": "MAC-0011",
    "name": "Drill Press",
    "category": "Machinery",
    "manufacturer": "Bosch",
    "brand": "Bosch",
    "model": "PBD 40",
    "unit": "Piece",
    "type": "Asset",
    "cost": 2500000,
    "reorder_level": 2,
},

{
    "item_code": "MAC-0012",
    "name": "Bench Grinder",
    "category": "Machinery",
    "manufacturer": "Bosch",
    "brand": "Bosch",
    "model": "GBG 60-20",
    "unit": "Piece",
    "type": "Asset",
    "cost": 1800000,
    "reorder_level": 2,
},

{
    "item_code": "MAC-0013",
    "name": "Hydraulic Press",
    "category": "Machinery",
    "manufacturer": "Enerpac",
    "brand": "Enerpac",
    "model": "H Frame 50T",
    "unit": "Piece",
    "type": "Asset",
    "cost": 19500000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0014",
    "name": "Air Compressor",
    "category": "Machinery",
    "manufacturer": "Atlas Copco",
    "brand": "Atlas Copco",
    "model": "GX5",
    "unit": "Piece",
    "type": "Asset",
    "cost": 9800000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0015",
    "name": "Metal Cutting Machine",
    "category": "Machinery",
    "manufacturer": "Bosch",
    "brand": "Bosch",
    "model": "GCO 220",
    "unit": "Piece",
    "type": "Asset",
    "cost": 2100000,
    "reorder_level": 2,
},

{
    "item_code": "MAC-0016",
    "name": "Industrial Generator",
    "category": "Machinery",
    "manufacturer": "Cummins",
    "brand": "Cummins",
    "model": "C220D5",
    "unit": "Piece",
    "type": "Asset",
    "cost": 145000000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0017",
    "name": "Forklift",
    "category": "Machinery",
    "manufacturer": "Toyota Material Handling",
    "brand": "Toyota",
    "model": "8FG25",
    "unit": "Piece",
    "type": "Asset",
    "cost": 98000000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0018",
    "name": "Industrial Air Dryer",
    "category": "Machinery",
    "manufacturer": "Atlas Copco",
    "brand": "Atlas Copco",
    "model": "FD 15",
    "unit": "Piece",
    "type": "Asset",
    "cost": 14000000,
    "reorder_level": 1,
},

{
    "item_code": "MAC-0019",
    "name": "Bench Vice",
    "category": "Machinery",
    "manufacturer": "Record",
    "brand": "Record",
    "model": "No.5",
    "unit": "Piece",
    "type": "Asset",
    "cost": 450000,
    "reorder_level": 3,
},

{
    "item_code": "MAC-0020",
    "name": "Portable Generator",
    "category": "Machinery",
    "manufacturer": "Honda",
    "brand": "Honda",
    "model": "EU70is",
    "unit": "Piece",
    "type": "Asset",
    "cost": 12500000,
    "reorder_level": 1,
},

]

LABORATORY_EQUIPMENT = [

# ================= Electronics =================

{
    "item_code": "LAB-0001",
    "name": "Digital Oscilloscope",
    "category": "Laboratory Equipment",
    "manufacturer": "Keysight Technologies",
    "brand": "Keysight",
    "model": "DSOX1102G",
    "unit": "Piece",
    "type": "Asset",
    "cost": 8500000,
    "reorder_level": 1,
},

{
    "item_code": "LAB-0002",
    "name": "Function Generator",
    "category": "Laboratory Equipment",
    "manufacturer": "Rigol",
    "brand": "Rigol",
    "model": "DG1022Z",
    "unit": "Piece",
    "type": "Asset",
    "cost": 2800000,
    "reorder_level": 1,
},

{
    "item_code": "LAB-0003",
    "name": "Digital Multimeter",
    "category": "Laboratory Equipment",
    "manufacturer": "Fluke",
    "brand": "Fluke",
    "model": "87V",
    "unit": "Piece",
    "type": "Asset",
    "cost": 1650000,
    "reorder_level": 5,
},

{
    "item_code": "LAB-0004",
    "name": "Programmable DC Power Supply",
    "category": "Laboratory Equipment",
    "manufacturer": "Rigol",
    "brand": "Rigol",
    "model": "DP832",
    "unit": "Piece",
    "type": "Asset",
    "cost": 3400000,
    "reorder_level": 2,
},

{
    "item_code": "LAB-0005",
    "name": "Logic Analyzer",
    "category": "Laboratory Equipment",
    "manufacturer": "Saleae",
    "brand": "Saleae",
    "model": "Logic Pro 8",
    "unit": "Piece",
    "type": "Asset",
    "cost": 5200000,
    "reorder_level": 1,
},

# ================= Mechatronics =================

{
    "item_code": "LAB-0006",
    "name": "PLC Training Kit",
    "category": "Laboratory Equipment",
    "manufacturer": "Siemens",
    "brand": "Siemens",
    "model": "S7-1200",
    "unit": "Piece",
    "type": "Asset",
    "cost": 12500000,
    "reorder_level": 1,
},

{
    "item_code": "LAB-0007",
    "name": "Industrial Robotics Trainer",
    "category": "Laboratory Equipment",
    "manufacturer": "Festo",
    "brand": "Festo",
    "model": "Robotino",
    "unit": "Piece",
    "type": "Asset",
    "cost": 85000000,
    "reorder_level": 1,
},

{
    "item_code": "LAB-0008",
    "name": "Pneumatic Training System",
    "category": "Laboratory Equipment",
    "manufacturer": "Festo",
    "brand": "Festo",
    "model": "TP101",
    "unit": "Piece",
    "type": "Asset",
    "cost": 18000000,
    "reorder_level": 1,
},

{
    "item_code": "LAB-0009",
    "name": "Hydraulic Training System",
    "category": "Laboratory Equipment",
    "manufacturer": "Festo",
    "brand": "Festo",
    "model": "TH101",
    "unit": "Piece",
    "type": "Asset",
    "cost": 22000000,
    "reorder_level": 1,
},

{
    "item_code": "LAB-0010",
    "name": "Arduino Starter Kit",
    "category": "Laboratory Equipment",
    "manufacturer": "Arduino",
    "brand": "Arduino",
    "model": "UNO R4",
    "unit": "Set",
    "type": "Asset",
    "cost": 420000,
    "reorder_level": 10,
},

# ================= Measurement =================

{
    "item_code": "LAB-0011",
    "name": "Digital Vernier Caliper",
    "category": "Laboratory Equipment",
    "manufacturer": "Mitutoyo",
    "brand": "Mitutoyo",
    "model": "500 Series",
    "unit": "Piece",
    "type": "Asset",
    "cost": 580000,
    "reorder_level": 5,
},

{
    "item_code": "LAB-0012",
    "name": "Outside Micrometer",
    "category": "Laboratory Equipment",
    "manufacturer": "Mitutoyo",
    "brand": "Mitutoyo",
    "model": "293 Series",
    "unit": "Piece",
    "type": "Asset",
    "cost": 720000,
    "reorder_level": 5,
},

{
    "item_code": "LAB-0013",
    "name": "Digital Weighing Scale",
    "category": "Laboratory Equipment",
    "manufacturer": "Ohaus",
    "brand": "Ohaus",
    "model": "Scout STX",
    "unit": "Piece",
    "type": "Asset",
    "cost": 1500000,
    "reorder_level": 2,
},

{
    "item_code": "LAB-0014",
    "name": "Infrared Thermometer",
    "category": "Laboratory Equipment",
    "manufacturer": "Fluke",
    "brand": "Fluke",
    "model": "62 MAX",
    "unit": "Piece",
    "type": "Asset",
    "cost": 920000,
    "reorder_level": 3,
},

{
    "item_code": "LAB-0015",
    "name": "Digital Tachometer",
    "category": "Laboratory Equipment",
    "manufacturer": "Extech",
    "brand": "Extech",
    "model": "461920",
    "unit": "Piece",
    "type": "Asset",
    "cost": 980000,
    "reorder_level": 2,
},

]
INVENTORY_CATALOG = (
    ICT_EQUIPMENT
    + MACHINERY
    + LABORATORY_EQUIPMENT
)