# Generated by Django 6.0.6 on 2026-07-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['section__campus__name', 'section__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['campus__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='unique_location_per_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('campus', 'name'), name='unique_section_per_campus'),
        ),
    ]
