# Generated by Django 6.0.6 on 2026-07-05 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_manufacturer_inventoryitem_brand_and_more'),
        ('organization', '0002_alter_location_options_alter_section_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetinstance',
            options={'ordering': ['asset_tag']},
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'ordering': ['name'], 'verbose_name': 'Asset Status', 'verbose_name_plural': 'Asset Statuses'},
        ),
        migrations.AlterModelOptions(
            name='inventoryassignment',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name', 'item_code']},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventoryassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetinstance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='assetinstance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='assetinstance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.assetstatus'),
        ),
        migrations.AlterField(
            model_name='inventoryassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.assetinstance'),
        ),
        migrations.AlterField(
            model_name='inventoryassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemtype'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unitofmeasure'),
        ),
    ]
