# Generated by Django 6.0.6 on 2026-07-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitionbatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='batchitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
    ]
