# Generated by Django 6.0.6 on 2026-07-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='requisitionline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['-created_at']},
        ),
    ]
